# -*- coding: utf-8 -*-
"""Strings.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1tbCzMi421mq0mk0rf9hZqNVUW_a9-Xyb
"""

# Concatenando
a = 'a'
b = 'b'
c = 'c'
d = 'd'

abcedário = a + b + c + d
print(abcedário)

"""Letras Maiúsculas"""

abcedário_maiscula = abcedário.upper()
print(abcedário_maiscula)

"""Letras Minúsculas"""

abcedário_minuscula = abcedário.lower()
print(abcedário_minuscula)

capitalize() converte o primeiro caractere em maiúscula
casefold()
