# -*- coding: utf-8 -*-
"""08_jogo_pedra_papel_tesoura.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1z79f1oTwZw5r_Aqbd_JLEaQ31HKUplNr
"""

from random import randint # Função randint que retorna um valor aleatório
t = ['Pedra','Papel','Tesoura'] # Cria uma lista com as opções
computador = t[randint(0,2)] # Coloca o computador para jogar dentro das opções
jogador = False # Coloca o jogador como False
while jogador == False:
    jogador = input('Pedra, Papel ou Tesoura? ')
    if jogador == computador:
        print('Empate!')
    elif jogador == 'Pedra':
        if computador == 'Papel':
            print('Você perdeu! ', computador, 'embrulha', jogador)
        else:
               print('Você venceu! ', jogador, 'esmaga', computador)
    elif jogador == 'Papel':
        if computador == 'Tesoura':
            print('Você perdeu! ', computador, 'corta', jogador)
        else:
            print('Você venceu! ', jogador, 'embrulha', computador) 
    elif jogador == 'Tesoura':
        if computador == 'Pedra': 
            print('Você perdeu! ', computador, 'esmaga', jogador)
        else:
            print('Você venceu!', jogador, 'corta', computador)
    else:
           print('Essa não é uma jogada válida. Verifique a ortografia!')
    jogador = False
    computador = t[randint(0,2)]