# -*- coding: utf-8 -*-
"""10_criando_código_random

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/17JYDvTTbEjeMpGXAMU7DnWHqY8CET5-n
"""

import random as rd

# Função que embaralha todos os caracteres de uma string
def embaralha(string):
    tempList = list(string)
    rd.shuffle(tempList)
    return ''.join(tempList)

# Gerar letras aleatórias
letra_1 = chr(rd.randint(65,90)) # Gera uma maíuscula aleatória (Com base no código ASCII)
letra_2 = chr(rd.randint(65,90)) # Gera uma maíuscula aleatória (Com base no código ASCII)
letra_3 = chr(rd.randint(65,90)) # Gera uma maíuscula aleatória (Com base no código ASCII)
letra_4 = chr(rd.randint(65,90)) # Gera uma maíuscula aleatória (Com base no código ASCII)
letra_5 = chr(rd.randint(65,90)) # Gera uma maíuscula aleatória (Com base no código ASCII)
# Aumentando o código aqui você consegue mais letras

num_1 = rd.randint(1,9) # Criando os números aleatórios
num_1 = str(num_1) # Torna o número passível de concatenação
num_2 = rd.randint(1,9) # Criando os números aleatórios
num_2 = str(num_2) # Torna o número passível de concatenação

# Gere senha usando todos os caracteres, em ordem aleatória
password = letra_1 + letra_2 + letra_3 + letra_4 + letra_5
password = embaralha(password)

# Saída
print(str(password) + num_1 + num_2)