# -*- coding: utf-8 -*-
"""11_calculadora.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KVOrU4HL8QwjUVDAwFRiNXnCwREADkmU
"""

def adicao(a,b):
    sum = a + b
    return sum

def subtracao(a,b):
    diff = a - b
    return diff

def multiplicacao(a,b):
    multi = a*b
    return multi

def divisao(a,b):
    divi = a/b
    return divi

a = int(input('Digite o primeiro número: '))
b = int(input('Digite o segundo número: '))

print() # Esse print serve para dar um espaço em branco
print() # Esse print serve para dar um espaço em branco

print('A soma entre os números é: ', adicao(a,b))
print('A diferença entre os números é: ', subtracao(a,b))
print('A multiplicação entre os números é: ', multiplicacao(a,b))
print('A divisão entre os números é: ', divisao(a,b))