# -*- coding: utf-8 -*-
"""Comparações, condições, Input, Loops

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KwM_QRUhl3t4phKfQ_eOltNhGlK6yVMU
"""

# Declarando as variáveis
a = 50
b = 100
c = 50

# Igual
if a == c:
    print('A é igual a C')

# Diferente
if a != b:
    print('A é diferente de B')

# Menor, menor ou igual que
if a < b:
    print('A é menor do que B')
if a <= b:
    print('A é menor ou igual a B')

# Maior que 
if b > c:
    print('B é maior do que C')

# Input Algorítmo Posso dirigir?
idade = int(input('Digite a sua idade: '))

if idade >= 18:
    print('Você já pode dirigir')
elif  idade < 18:
    print('Você ainda não pode dirigir')

#Input Algorítmo Exercício
exercicio = int(input('Quantos minutos você se exercita por dia? '))

if exercicio < 30:
    print('Você deveria se exercitar mais')
elif exercicio >= 30 and exercicio <=60:
    print('Você está no caminho certo')
elif exercicio > 60 and exercicio <= 120:
    print(' Você é um(a) atleta')
else:
    print('Uau, você se exercita muito')