# -*- coding: utf-8 -*-
"""Funções.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/11vGbz7kzV5VsNtjjOrtIIuCrSc57SXu_

Cria uma função de cálculo de IMC
"""

def imc(peso, altura):
    print(peso/altura**2)
imc(80, 1.65)

"""Cria um loop que escreve até o 19."""

num = 0
while num < 20:
    print(num)
    num += 1

"""Imprime os números de 0 à 10, de 2 em 2."""

for i in range(0, 10, 2):
    print(i)

"""Cria um loop que escreve até o número 03."""

numeros = [1,2,3,4,5,6,7,8,9,10]
for x in numeros:
    print(x)
    if x == 3:
        break

"""Cria um loop que escreve até o 10, e pula o 06."""

num = 0
while num < 10:
    num += 1
    if num == 6:
        continue
    print(num)