# -*- coding: utf-8 -*-
"""jogo_adivinhacao.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_jooH_jYxJDg9Nw1URlTcDMPxy25Pmn0
"""

import random
n = random.randint(1,99)
adivinhe = int(input('Tente adivinhar um núemero entre 1 e 99'))
while n != 'adivinhe': # Enquanto o n for diferente da variável adivinhe
    if adivinhe < n:
        print('O número é maior que este')
        adivinhe = int(input('Tente outra vez:'))
    elif adivinhe > n:
        print('O número é menor que este')
        adivinhe = int(input('Tente outra vez:'))
    else:
        print ('Você acertou!')
        break # Serve para 'parar o loop