# -*- coding: utf-8 -*-
"""primeiro-contato.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1m0HJ5P898ZYtgxjZ57WAJvtgglXUIWVq
"""

# A função print imprime um resultado
print ('Olá mundo') 
print ('Estou adorando o bootcamp de Python')
print ('Vou beber um copo d\'água')
print ("Vou compartilhar com meus amigos sobre o bootcamp")

# Operações em Python
print(5) 
print(5+5)
print(2*8)
print(50/2)

# Condicionais
if 10 > 11: 
   print ('10 é maior do que 11')
else:
  print('10 não é maior que 11!')
a = 50
b = 100
c = 50
# Igual
if a == c:
    print('A é igual a C')
# Diferente
if a != b:
    print('A é diferente de B')
# Menor, menor ou igual que
if a < b:
    print('A é menor do que B')
if a <= b:
    print('A é menor ou igual a B')
# Maior que 
if b > c:
    print('B é maior do que C')

# Criando uma variável
numero = 5 
Python = 'Melhor linguagem de Programação'
num_pi = 3.14
soma = 5+5 
print(numero)
print(Python)
print(num_pi)
print(soma)

''' 
A partir do momento que coloquei três aspas simples, tudo o que 
eu escrever aqui dentro será considerado comentário. 
É muito útil quando queremos explicar alguma coisa, ou deixar 
instruções dentro ou antes do código. 
'''
""" 
O mesmo ocorre com as aspas duplas. 
Você pode escolher o que você quer usar. 
A comunidade Python recomenda usar as aspas simples, mas fica a 
seu critério escolher. 
"""

# Variáveis: Strings
cidade = 'Belo Horizonte'
lugar = 'IGTI'
curso = 'Desenvolvedor Python'
prof = 'Erick Faria'
aluno = 'Samara'

# Integer
num_alunos = (1580)
num_habitantes = (3000)
num_alunos = int(1580) # Assegura que os dados inputados sejam int
num_habitantes = int(3000)

#Float
distancia_km = (10.25)
altura = (1.75)
peso = (71.2)
distancia_km = float(10.25) # Assegura que os dados inputados sejam float
altura = float(1.75)
peso = float(71.2)

# Exemplo de uma list
distancia_km = [85.45,98.45, 55.21]
print(distancia_km)

# Exemplo de uma tuple: são imutáveis, portanto não é possível modificar o conteúdo sem sobrescrever a variável que a representa
altura_alunos = (1.55,1.75,1.84)
print(altura_alunos)

# Dicionários
# Definindo código das UF's do sudeste brasileiro
uf_sud = {'MG':31, 'SP':35, 'RJ':33, 'ES':32}
# Definindo código da capital do Amazonas
cod_manaus = {'Manaus':1302603}
# Definindo o gentílico de quem nasce em Manaus
gentílico = {'Manaus':'manauara'}
cod_uf = {
11 : 'Rondônia',
12 : 'Acre',
13 : 'Amazonas',
14 : 'Roraima',
15 : 'Pará',
16 : 'Amapá',
17 : 'Tocantins',
21 : 'Maranhão',
22 : 'Piauí',
23 : 'Ceará',
24 : 'Rio Grande do Norte',
25 : 'Paraíba',
26 : 'Pernambuco',
27 : 'Alagoas',
28 : 'Sergipe',
29 : 'Bahia',
31 : 'Minas Gerais',
32 : 'Espírito Santo',
33 : 'Rio de Janeiro',
35 : 'São Paulo',
41 : 'Paraná',
42 : 'Santa Catarina',
43 : 'Rio Grande do Sul',
50 : 'Mato Grosso do Sul',
51 : 'Mato Grosso',
52 : 'Goiás',
53 : 'Distrito Federal'}

# Sets
'''
Os sets são utilizados para armazenar múltiplos valores, assim como os 
anteriores, porém com algumas particularidades: 
Os valores não podem ser duplicados. 
O set não pode ser modificado. 
Os valores não são indexados. 
Os valores são fora de ordem. 
'''
frutas = {'maçã', 'mamão', 'uva', 'abacate', 'melão'}
series = {'Friends', 'Big Bang Theory', 'Lost', 'House'}
num_vacinas = {25, 21, 215, 214, 5648, 5486}

# If, Elif e Else
idade = 18 
if idade < 12:
   print('crianca')
elif idade < 18:
   print('adolescente')
elif idade < 60:
   print('adulto')
else:
   print('idoso')

# Função For
for i in range(0,26):
 print(i)

# Função For listando nomes
nomes = ['João', 'Maria', 'José', 'Geraldo', 'Sebastião']
for i in nomes:
   print(i)

# Função While
numero = 0
while numero <=50:
   numero += 1
   print(numero)

# Criando uma função
def area(point1, point2):
    y2] = point2 
   return (x1*y2 - y1*x2)/2
area([6,2],[2,3])

# Como o Python salva as Strings
nome = 'pão'
print(nome.encode())
nome2 = 'Uma varíavel muito grande'
print(nome2.encode())

# Convertendo dados em Python
num_end = 200
num_end_x = str(num_end)
print (type(num_end_x))

num_end = '200'
num_end_x = int(num_end)
print (type(num_end_x))

#Concatenação
texto = 'olá,'
numero = 5
print(texto, numero)

# Printando listas
lista_compras = ['pera', 'maçã', 'uva']
b = ",".join(lista_compras[0:2])
print(b)